In [1]:
import pandas as pd
import yfinance as yf

In [2]:
from datetime import datetime

Ticker = 'UBER'
CURRENT_MONTH = datetime.now().strftime('%Y-%m')

In [3]:
# Fetch the ticker data
TICKER = yf.Ticker(Ticker)
# Get the EPS estimate
eps_trend = TICKER.eps_trend

# Calculate percent change from 7, 30, 60, 90 days ago to current
eps_trend['7d_change%'] = (eps_trend['current'] - eps_trend['7daysAgo']) / eps_trend['7daysAgo'] * 100
eps_trend['30d_change%'] = (eps_trend['current'] - eps_trend['30daysAgo']) / eps_trend['30daysAgo'] * 100
eps_trend['60d_change%'] = (eps_trend['current'] - eps_trend['60daysAgo']) / eps_trend['60daysAgo'] * 100
eps_trend['90d_change%'] = (eps_trend['current'] - eps_trend['90daysAgo']) / eps_trend['90daysAgo'] * 100

eps_trend

,current,7daysAgo,30daysAgo,60daysAgo,90daysAgo,7d_change%,30d_change%,60d_change%,90d_change%
0q,0.49959,0.49216,0.48334,0.47914,0.47545,1.509672,3.362023,4.268064,5.077295
+1q,0.46685,0.48454,0.49723,0.49428,0.49324,-3.650885,-6.109849,-5.549486,-5.350337
0y,1.82084,1.07658,1.06867,1.04968,1.03467,69.131881,70.383748,73.466199,75.982680
+1y,2.28894,2.23226,2.21971,2.20373,2.17613,2.539131,3.118876,3.866626,5.183973

In [4]:
# Fetch the historical market data
hist = TICKER.history(period="3mo")

# Calculate the 50-day average volume
average_volume_50d = hist['Volume'].rolling(window=50).mean().iloc[-1]

print(f'Average 50 days volumn: {average_volume_50d}')

Average 50 days volumn: 18135572.6

In [5]:
TICKER.earnings_dates

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2025-10-29 08:00:00-04:00           NaN           NaN          NaN
2025-08-04 08:00:00-04:00           NaN           NaN          NaN
2025-05-06 08:00:00-04:00           NaN           NaN          NaN
2025-02-05 08:00:00-05:00          0.50           NaN          NaN
2024-10-31 06:00:00-04:00          0.41          1.20       1.9126
2024-08-06 06:00:00-04:00          0.31          0.47       0.5139
2024-05-08 07:00:00-04:00          0.23         -0.31      -2.3541
2024-02-07 06:00:00-05:00          0.17          0.66       2.9232
2023-11-07 06:00:00-05:00          0.12          0.10      -0.1786
2023-08-01 06:00:00-04:00         -0.01          0.18      19.2927
2023-05-02 06:00:00-04:00         -0.09         -0.08       0.0767
2023-02-08 06:00:00-05:00         -0.18          0.29       2.5769

In [6]:
PATH = '/Users/nick0o0o0/Library/Mobile Documents/com~apple~CloudDocs/gxyfile/Trading/Stocks_selection/report'
FILE = f'{PATH}/{CURRENT_MONTH}/{Ticker}_smallfundamental.csv'

In [7]:
df = pd.read_csv(FILE)

In [8]:
df.head(30)

,fiscalDateEnding,quarter,reportedEPS,EPS_YOY_pct_change,estimatedEPS,surprise,totalRevenue,revenue_YOY_pct_change,netIncome,netIncome_YOY_pct_change,netProfitMargin,netProfitMargin_YOY_pct_change
0,2024-09-30,2024Q3,1.20,+1100.0,0.41,0.79,11188000000,+20.0,2612000000,+1082.0,0.233464,+882.0
1,2024-06-30,2024Q2,0.47,+161.0,0.31,0.16,10700000000,+16.0,1015000000,+158.0,0.094860,+122.0
2,2024-03-31,2024Q1,-0.31,+287.0,0.23,-0.54,10131000000,+15.0,-654000000,+317.0,-0.064554,+263.0
3,2023-12-31,2023Q4,0.66,+128.0,0.17,0.49,9936000000,+15.0,1429000000,+140.0,0.143820,+108.0
4,2023-09-30,2023Q3,0.10,-116.0,0.12,-0.02,9292000000,+11.0,221000000,-118.0,0.023784,-116.0
5,2023-06-30,2023Q2,0.18,-114.0,-0.01,0.19,9230000000,+14.0,394000000,-115.0,0.042687,-113.0
6,2023-03-31,2023Q1,-0.08,-56.0,-0.09,0.01,8823000000,+29.0,-157000000,-97.0,-0.017794,-98.0
7,2022-12-31,2022Q4,0.29,-212.0,-0.18,0.47,8607000000,+49.0,595000000,-33.0,0.069130,-55.0
8,2022-09-30,2022Q3,-0.61,+177.0,-0.22,-0.39,8343000000,+72.0,-1206000000,-50.0,-0.144552,-71.0
9,2022-06-30,2022Q2,-1.33,+600.0,-0.26,-1.07,8073000000,+105.0,-2601000000,-327.0,-0.322185,-211.0
10,2022-03-31,2022Q1,-0.18,-169.0,-0.24,0.06,6854000000,+136.0,-5930000000,+5391.0,-0.865188,+2226.0
11,2021-12-31,2021Q4,-0.26,-52.0,-0.35,0.09,5778000000,+83.0,892000000,-192.0,0.154379,-150.0
12,2021-09-30,2021Q3,-0.22,-65.0,-0.30,0.08,4845000000,+72.0,-2424000000,+123.0,-0.500310,+29.0
13,2021-06-30,2021Q2,-0.19,-76.0,-0.51,0.32,3929000000,+105.0,1144000000,-164.0,0.291168,-131.0
14,2021-03-31,2021Q1,0.26,-141.0,-0.54,0.80,2903000000,-11.0,-108000000,-96.0,-0.037203,-96.0
15,2020-12-31,2020Q4,-0.54,-16.0,-0.56,0.02,3165000000,+8.0,-969000000,-12.0,-0.306161,-18.0
16,2020-09-30,2020Q3,-0.62,-9.0,-0.65,0.03,2813000000,-26.0,-1089000000,-6.0,-0.387131,+27.0
17,2020-06-30,2020Q2,-0.80,-83.0,-0.86,0.06,1913000000,-40.0,-1775000000,-66.0,-0.927862,-44.0
18,2020-03-31,2020Q1,-0.64,-71.0,-0.88,0.24,3248000000,+5.0,-2936000000,+190.0,-0.903941,+177.0
19,2019-12-31,2019Q4,-0.64,-66.0,-0.68,0.04,2922000000,+37.0,-1096000000,+24.0,-0.375086,-10.0
20,2019-09-30,2019Q3,-0.68,+nan,-0.81,0.13,3813000000,+30.0,-1162000000,+18.0,-0.304747,-9.0
21,2019-06-30,2019Q2,-4.77,+nan,-3.19,-1.58,3166000000,+14.0,-5236000000,+496.0,-1.653822,+421.0
22,2019-03-31,2019Q1,-2.23,+nan,-2.26,0.03,3099000000,+20.0,-1012000000,-127.0,-0.326557,-123.0
23,2018-12-31,2018Q4,-1.86,+nan,0.00,-1.86,2137000000,+nan,-887000000,+nan,-0.415068,+nan
24,2018-09-30,2018Q3,NaN,+nan,NaN,NaN,2944000000,+nan,-986000000,+nan,-0.334918,+nan
25,2018-06-30,2018Q2,NaN,+nan,NaN,NaN,2768000000,+nan,-878000000,+nan,-0.317197,+nan
26,2018-03-31,2018Q1,NaN,+nan,NaN,NaN,2584000000,+nan,3748000000,+nan,1.450464,+nan